import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Button
import androidx.compose.material3.Text
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.res.stringResource
import com.example.cupcake.R
import com.example.cupcake.ui.components.DeepNested1
import com.example.cupcake.ui.components.Spacer

// Log.d("XXX", data.value?.toString() ?: "default")

Column(
    verticalArrangement = Arrangement.SpaceBetween,
    modifier =
        Modifier
            .fillMaxHeight()
            .padding(dimensionResource(R.dimen.padding_medium)),
) {
    Column(
        modifier = Modifier.fillMaxWidth(),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.spacedBy(dimensionResource(R.dimen.padding_small)),
    ) {

        Spacer()
        // Coffee()
        // Simple(good="buh-bye")
        // ReactiveAssignments()
        // ReactiveDeclarations()
        // ReactiveStatements()
        // Nested(answer=42)
        // Nested()
        // If()
        // If()
        // Loop()
        // BindingText()
        // ComponentBindings()
        DeepNested1()
        Button(onClick={
            println("---")
        }
        ) { Text(stringResource(R.string.home)) }
    }

    Column(
        modifier = Modifier.fillMaxWidth(),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement =
            Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_medium)),
    ) {
        Row(horizontalArrangement = Arrangement.SpaceEvenly) {
            Button(
                onClick = { navController.navigate("/") },
            ) { Text(stringResource(R.string.home)) }

            Button(
                onClick = { navController.navigate("/blog") },
            ) { Text(stringResource(R.string.blog)) }

            Button(
                onClick = { navController.navigate("/settings") },
            ) { Text(stringResource(R.string.settings)) }

            Button(
                onClick = { navController.navigate("/about") },
            ) { Text(stringResource(R.string.about)) }
        }
    }
}
