import androidx.compose.material3.Text
import androidx.compose.material3.Button
import androidx.compose.material3.TextField
import androidx.compose.ui.text.input.TextFieldValue
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.ui.text.TextRange



var $text = TextFieldValue()
//var text2 by rememberSaveable(stateSaver = TextFieldValue.Saver) { mutableStateOf(TextFieldValue("", TextRange(0, 7))) }
var *text4 = TextFieldValue("", TextRange(0, 7))
var *text3(stateSaver=TextFieldValue.Saver) = TextFieldValue("", TextRange(0, 7))
var text2 by rememberSaveable(stateSaver = TextFieldValue.Saver) { mutableStateOf(TextFieldValue("", TextRange(0, 7))) }

BasicTextField(value=text, onValueChange={text=it})
TextField(value=text2, onValueChange={text2=it})
Text("Entered ${text2.text}")
