import androidx.compose.material3.Text
import androidx.compose.material3.Button
import androidx.compose.material3.TextField
import androidx.compose.ui.text.input.TextFieldValue
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.ui.text.TextRange


var *text2(stateSaver = TextFieldValue.Saver)  = TextFieldValue("", TextRange(0, 7))

TextField(value=text2, onValueChange={text2=it})
Text("Entered ${text2.text}")
