import androidx.compose.material3.Text
import androidx.compose.material3.Button
import androidx.compose.material3.TextField

import com.example.cupcake.utils.*

import com.example.cupcake.ui.components.Keypad


var *first: Int = 0
var *second: Int = 0

var *pin = ""

fun handleSubmit() {
  println("You entererd $pin")
}

Text("OUTSIDE: pin=$pin first=$first second=$second")
    
Button(onClick={
  first = first + 1
  }) {
Text( text = "OUTSIDE (2way): $first")
}

Button(onClick={
  second = second + 1
  }) {
Text( text = "OUTSIDE (1way): $second")
}
Keypad(value=pin, bind:first = first, second=second)
//Keypad(value=pin, bind:v = v)
