---
import kotlinx.coroutines.flow.MutableStateFlow

class ViewModel {
    var first = MutableStateFlow(0)
    var second = MutableStateFlow(0)
}
---
import androidx.compose.material3.Text
import androidx.compose.material3.Button
import androidx.compose.material3.TextField

import com.example.cupcake.utils.*

import com.example.cupcake.ui.components.Keypad

val viewModel = remember { ViewModel() } // or viewModel() etc.
var (first, setFirst) = viewModel.first.collectAsMutableState()
//var (second, setSecond) = viewModel.second.collectAsMutableState()

var *second = 0



var *pin = ""

fun handleSubmit() {
  println("You entererd $pin")
}

Text("OUTSIDE: pin=$pin first=$first second=$second")
    
Button(onClick={
  first = first + 1
  setFirst(first)
  }) {
Text( text = "OUTSIDE (2way): $first")
}

Button(onClick={
  second = second + 1
  }) {
Text( text = "OUTSIDE (1way): $second")
}
Keypad(value=pin, first = first, second=second)
//Keypad(value=pin, bind:v = v)
