import androidx.compose.material3.Text
import androidx.compose.material3.Button
import androidx.compose.runtime.derivedStateOf
import androidx.compose.runtime.*



println("[components/computed-good.pine]: Top")

var *count = 0
val doubled by remember { derivedStateOf{ count * 2 }}

onCreate {
  println("[components/computed-good.pine]: onCreate")
}

ui {

  Text("Computed Good")
  Text("count=$count, doubled=$doubled")

  Button(onClick={count = count + 1}) {
    Text("count++")
  }


}
