---
import kotlinx.coroutines.flow.MutableStateFlow

class ViewModel {
    val first = MutableStateFlow("")
}
---
import androidx.compose.material3.Text
import androidx.compose.material3.Button
import androidx.compose.material3.TextField

import com.example.cupcake.utils.*

import com.example.cupcake.ui.components.Keypad

val viewModel = remember { ViewModel() } // or viewModel() etc.
val (first, setFirst) = viewModel.first.collectAsMutableState()



var *pin = ""

fun handleSubmit() {
  println("You entererd $pin")
}

Text("OUTSIDE: pin=$pin first=$first")
    TextField(
        value = first,
        onValueChange = setFirst
    )
Keypad(value=pin, first = first, setFirst = setFirst)
//Keypad(value=pin, bind:v = v)
