import androidx.compose.material3.Text
import androidx.compose.material3.Button
import kotlin.time.Duration.Companion.seconds
import androidx.compose.runtime.mutableStateOf
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import androidx.compose.runtime.rememberCoroutineScope




println("[components/counter.pine]: Top")

val scope = rememberCoroutineScope()

var *count : Int = 0

var *ticks = 0

suspend fun start() {
  ticks  = 0
  while(true) {
  println("[components/counter.pine]: while $ticks")
      delay(1.seconds)
      ticks++
  }
}

on_create {
  println("[components/counter.pine]: on_create")
}

on_destroy {
  println("[components/counter.pine]: on_destroy")
}


ui {
  Text(text="ticks: $ticks")
  Text(text="Count: $count ticks: ${ticks}")

  Button(onClick={
  println("[components/counter.pine]: click $count")
      ticks = ticks + 1
    }) {
      Text(text="Click Me")
  }
}
