import androidx.compose.material3.Text
import androidx.compose.material3.Button
import androidx.compose.material3.TextField

import com.example.cupcake.utils.*

import com.example.cupcake.ui.components.DeepNested3


println(" 2. Render")
external var first: Int

onCreate {
  println(" 2. onCreate")
}

ui {
  Button(onClick={

    println("----")

    first = first + 1
    }) {
    Text( text = "2: $first")
  }

  DeepNested3(bind:first=first)
}
