import androidx.compose.material3.Text
import androidx.compose.material3.Button
import androidx.compose.material3.TextField

import com.example.cupcake.utils.*

import com.example.cupcake.ui.components.DeepNested3


println(" 2. top")
external var first: Int

LaunchedEffect(true) {
  println("Loaded 2")
}

Button(onClick={
  first = first + 1
  }) {
  Text( text = "2: $first")
}

DeepNested3(bind:first=first)

println(" 2. bottom")
