import androidx.compose.material3.Text
import androidx.compose.material3.Button
import androidx.compose.runtime.mutableStateMapOf


println("if - before")
var $count = 0
val $user = mutableStateMapOf("loggedIn" to false)
println("if - after")

if (user["loggedIn"] == false) {
Button(onClick={ 
  user["loggedIn"] = true
  }){
  Text(text="Log in ")
}
}
else {

Button(onClick={ 
  user["loggedIn"] = false
  }){
  Text(text="Log out ")
}
}
