import androidx.compose.foundation.layout.Row
import androidx.compose.material3.Button
import androidx.compose.material3.Text
import androidx.compose.material3.TextField

external var first: Int = 0
external var second: Int = 0

println("first=$first, second=$second")

external var *value: String = ""

external var setFirst: (Int) -> Unit

fun select(num: Int) {
  value = Regex("\\w").replace(value, "x") + num.toString()
  println("Here $num $value ")
}

//println("INSIDE - params - $params")

Text(text="INSIDE: value=$value first=$first second=$second")

Button(onClick={
  first = first + 1
  setFirst(first)
  }) {
Text( text = "INSIDE (2way): $first")
}

Button(onClick={
  println(second)
  second = second + 1
  println(second)
  }) {

Text( text = "INSIDE (1way): $second")
}

Row() {
  Button(onClick={select(1)}){Text(text="1")}
  Button(onClick={select(2)}){Text(text="2")}
  Button(onClick={select(3)}){Text(text="3")}

}


Row() {
  Button(onClick={select(4)}){Text(text="4")}
  Button(onClick={select(5)}){Text(text="5")}
  Button(onClick={select(6)}){Text(text="6")}

}


Row() {
  Button(onClick={select(7)}){Text(text="7")}
  Button(onClick={select(8)}){Text(text="8")}
  Button(onClick={select(9)}){Text(text="9")}
}


Row() {
  Button(onClick={}){Text(text="Clear")}
  Button(onClick={}){Text(text="0")}
  Button(onClick={}){Text(text="Submit")}
}
