import androidx.compose.material3.Button
import androidx.compose.material3.Text

external var value

Row() {
  Button(){Text(text="1")}
  Button(){Text(text="2")}
  Button(){Text(text="3")}

}


Row() {
  Button(){Text(text="4")}
  Button(){Text(text="5")}
  Button(){Text(text="6")}

}


Row() {
  Button(){Text(text="7")}
  Button(){Text(text="8")}
  Button(){Text(text="9")}
}


Row() {
  Button(){Text(text="Clear")}
  Button(){Text(text="0")}
  Button(){Text(text="Submit")}
}
