---
data class Photo (
  val id: String,
  val author: String,
  val width: Int,
  val height: Int,
  val url: String,
  val download_url: String
)
---

import com.hypercubetools.ktor.moshi.moshi
import io.ktor.client.HttpClient
import io.ktor.client.engine.cio.CIO
import io.ktor.client.plugins.contentnegotiation.ContentNegotiation
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import io.ktor.client.request.*
import io.ktor.client.call.body
import com.example.cupcake.utils.http

import androidx.compose.material3.Text
import androidx.compose.material3.Button

var *photos = listOf<Photo>()

LaunchedEffect(true) {
  println("onMount - A")
  photos = http.get("https://picsum.photos/v2/list?limit=10").body<List<Photo>>()
  println("onMount - C $photos")
}

ui {
  Text(text = "Photos - ${photos.size}")
}
