---
import kotlinx.coroutines.flow.MutableStateFlow
import androidx.compose.runtime.MutableState

 class ViewModel {
    val v = MutableStateFlow("")
    val first = MutableStateFlow(0)
    val c = MutableStateFlow(0)
    var signal = MutableStateFlow(0)
 }
---
import androidx.compose.material3.Text
import androidx.compose.material3.Button
import com.example.cupcake.ui.components.ComplexButton
import com.example.cupcake.ui.components.Counter

println("[components/reactivity.pine]: Top")

onCreate {
  println("[components/reactivity.pine]: onCreate")
}

ui {

  Counter()
  Counter()

}
