import androidx.compose.material3.Text
import androidx.compose.material3.Button
import androidx.compose.runtime.derivedStateOf
import androidx.compose.runtime.setValue
import androidx.compose.runtime.remember
import androidx.compose.runtime.getValue
import androidx.compose.runtime.SideEffect

var *count = 1

fun check() {
  println("The $count is ridiculously high")
}

SideEffect {println("hi there $count")}

fun handleClick() {
  count++
}




Button(onClick={handleClick()}) {
  Text(text = "RS: Count: $count")
}
