---
import kotlinx.coroutines.flow.MutableStateFlow
import androidx.compose.runtime.MutableState

 class ViewModel {
    val v = MutableStateFlow("")
    val first = MutableStateFlow(0)
    val c = MutableStateFlow(0)
    var signal = MutableStateFlow(0)
 }
 

---
import androidx.compose.material3.Text
import androidx.compose.material3.Button

println("[components/reactivity.pine]: Top")

var *signal = 0

ui {

  Button(onClick={
    signal = signal + 1
  }) {

    Text(text="hi - ${signal}")
  }

}
