import androidx.compose.material3.Text
import androidx.compose.material3.Button

import com.example.cupcake.ui.components.ComplexButton

println("[components/reactivity.pine]: Top")


ComplexButton() {
var *count: Int = 0
Text(text="Simple count: $count")

Button(onClick={
  count = count + 1
}) {
  Text(text="Simple: Click me")
}

}


//Text(text=text)
//
//Button(onClick={
//  count = count + 1
//}) {
//  Text(text="Complex: Click me")
//}


ComplexButton() {
var *count: Int = 0
  Text(text="Complex count: $count")
Text(text="Simple count: $count")
  Button(onClick={
    count = count + 1
  }) {
    Text(text="Simple: Click me")
  }
}
