import androidx.compose.material3.Text
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.rememberCoroutineScope
import kotlinx.coroutines.launch

external var good:String="bye"
var foo = "foo-value"
var *bar = "bar-value"
var $baz = "baz-value"
var x = 1
var y = 2
println("------------------")
println("This is a test")

val scope = rememberCoroutineScope()
LaunchedEffect(true) {
        println("LaunchedEffect: $x $y")

        x = 10
        y = 20

        println("LaunchedEffect: $x $y")
}

scope.launch {

        println("scope.launch: $x $y")
        x = 100
        y = 200
        println("scope.launch: $x $y")

}

DisposableEffect(scope) {
        println("DisposableEffect: $x $y")
        onDispose {
        println("DisposableEffect:onDispose : $x $y")

        }
}


Text("Simple $foo $bar $baz")
Text("x=$x y=$y")
