Column(modifier = modifier, verticalArrangement = Arrangement.SpaceBetween) {
    Column(
            modifier = Modifier.fillMaxWidth(),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.spacedBy(dimensionResource(R.dimen.padding_small))
    ) {}
    Column(
            modifier = Modifier.fillMaxWidth(),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement =
                    Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_medium))
    ) {
        Row(horizontalArrangement = Arrangement.SpaceEvenly) {
            Button(
                    onClick = { navController.navigate("/first") },
            ) { Text(stringResource(R.string.one)) }
            Button(
                    onClick = { navController.navigate("/second") },
            ) { Text(stringResource(R.string.two)) }

            Button(
                    onClick = { navController.navigate("/third") },
            ) { Text(stringResource(R.string.three)) }
        }
    }
}
